# Data Wrangling project

## Introduction

This project deals with datasets from applicants who applied for positions in various given departments. The applicants are then processed according to their personality scores which will determine the outcome of their applications, based on calculations done in the project.

## Importing modules

The modules are imported as they are modules that are necessary for completing the calculations and illustrations associated with the project.

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

## Importing the personality scores dataset

The CSV file is imported so that the dataset can be used to create a personality data frame.

In [2]:
raw_personality_df = pd.read_csv("../data/personality_scores.csv", sep=";")

The first five entries in the newly created and unedited data frame will be shown.

In [3]:
raw_personality_df.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Information is provided on the newly created data frame's columns.

In [4]:
raw_personality_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1558 entries, 0 to 1557
Data columns (total 70 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   ID                                                                        1558 non-null   int64
 1   Section 5 of 6 [I am always prepared.]                                    1558 non-null   object
 2   Section 5 of 6 [I am easily disturbed.]                                   1558 non-null   object
 3   Section 5 of 6 [I am exacting (demanding) in my work.]                    1558 non-null   object
 4   Section 5 of 6 [I am full of ideas.]                                      1558 non-null   object
 5   Section 5 of 6 [I am interested in people.]                               1558 non-null   object
 6   Section 5 of 6 [I am not interested in abstract ideas.]                   1558 non-null   object
 7   Section 5 of 6 [I am not interested in other people's problems.]          1558 non-null   object
 8   Section 5 of 6 [I am not really interested in others.]                    1558 non-null   object
 9   Section 5 of 6 [I am quick to understand things.]                         1558 non-null   object
 10  Section 5 of 6 [I am quiet around strangers.]                             1558 non-null   object
 11  Section 5 of 6 [I am relaxed most of the time.]                           1558 non-null   object
 12  Section 5 of 6 [I am the life of the party.]                              1558 non-null   object
 13  Section 5 of 6 [I change my mood a lot.]                                  1558 non-null   object
 14  Section 5 of 6 [I do not have a good imagination.]                        1558 non-null   object
 15  Section 5 of 6 [I don't like to draw attention to myself.]                1558 non-null   object
 16  Section 5 of 6 [I don't mind being the center of attention.]              1558 non-null   object
 17  Section 5 of 6 [I don't talk a lot.]                                      1558 non-null   object
 18  Section 5 of 6 [I feel comfortable around people.]                        1558 non-null   object
 19  Section 5 of 6 [I feel little concern for others.]                        1558 non-null   object
 20  Section 5 of 6 [I feel others' emotions.]                                 1558 non-null   object
 21  Section 5 of 6 [I follow a schedule.]                                     1558 non-null   object
 22  Section 5 of 6 [I get chores done right away.]                            1558 non-null   object
 23  Section 5 of 6 [I get irritated easily.]                                  1558 non-null   object
 24  Section 5 of 6 [I get stressed out easily.]                               1558 non-null   object
 25  Section 5 of 6 [I get upset easily.]                                      1558 non-null   object
 26  Section 5 of 6 [I have a rich vocabulary.]                                1558 non-null   object
 27  Section 5 of 6 [I have a soft (kind) heart.]                              1558 non-null   object
 28  Section 5 of 6 [I have a vivid imagination.]                              1558 non-null   object
 29  Section 5 of 6 [I have difficulty understanding abstract ideas.]          1558 non-null   object
 30  Section 5 of 6 [I have excellent ideas.]                                  1558 non-null   object
 31  Section 5 of 6 [I have frequent mood swings.]                             1558 non-null   object
 32  Section 5 of 6 [I have little to say.]                                    1558 non-null   object
 33  Section 5 of 6 [I insult people.]                                         1558 non-null   object
 34  Section 5 of 6 [I keep in the background.]                                1558 non-null   object
 35  Section 5 of 6 [I leave my belongings lying around.]                      1558 non-null   object
 36  Section 5 of 6 [I like order.]                                            1558 non-null   object
 37  Section 5 of 6 [I make a mess of things.]                                 1558 non-null   object
 38  Section 5 of 6 [I make people feel at ease.]                              1558 non-null   object
 39  Section 5 of 6 [I neglect my duties.]                                     1558 non-null   object
 40  Section 5 of 6 [I often feel blue (down).]                                1558 non-null   object
 41  Section 5 of 6 [I often forget to put things back in their proper place]  1558 non-null   object
 42  Section 5 of 6 [I pay attention to details.]                              1558 non-null   object
 43  Section 5 of 6 [I seldom feel blue (down).]                               1558 non-null   object
 44  Section 5 of 6 [I spend time reflecting on things.]                       1558 non-null   object
 45  Section 5 of 6 [I start conversations.]                                   1558 non-null   object
 46  Section 5 of 6 [I sympathize with others' feelings.]                      1558 non-null   object
 47  Section 5 of 6 [I take time out for others.]                              1558 non-null   object
 48  Section 5 of 6 [I talk to a lot of different people at parties.]          1558 non-null   object
 49  Section 5 of 6 [I use difficult words.]                                   1558 non-null   object
 50  Section 5 of 6 [I worry about things.]                                    1558 non-null   object
 51  Unnamed: 51                                                               0 non-null      float64
 52  Unnamed: 52                                                               0 non-null      float64
 53  Unnamed: 53                                                               0 non-null      float64
 54  Unnamed: 54                                                               0 non-null      float64
 55  Unnamed: 55                                                               0 non-null      float64
 56  Unnamed: 56                                                               0 non-null      float64
 57  Unnamed: 57                                                               0 non-null      float64
 58  Unnamed: 58                                                               0 non-null      float64
 59  Unnamed: 59                                                               0 non-null      float64
 60  Unnamed: 60                                                               0 non-null      float64
 61  Unnamed: 61                                                               0 non-null      float64
 62  Unnamed: 62                                                               0 non-null      float64
 63  Unnamed: 63                                                               0 non-null      float64
 64  Unnamed: 64                                                               0 non-null      float64
 65  Unnamed: 65                                                               0 non-null      float64
 66  Unnamed: 66                                                               0 non-null      float64
 67  Unnamed: 67                                                               0 non-null      float64
 68  Unnamed: 68                                                               0 non-null      float64
 69  IPIP_HIGH_RISK                                                            0 non-null      float64
dtypes: float64(19), int64(1), object(50)
memory usage: 852.2+ KB

The information above indicates that there are columns with null entries. Given that the data frame that will be created may not have any null entries, the dataset needs to be cleaned by dropping all the columns in the data frame with empty and null entries. Furthermore, the names of the columns are not satisfactory and will need to be reformatted.

The null and duplicate values and columns are dropped as they could negatively affect the quality and outcome of the analysis. Given that in this project there are individuals who are being critiqued and assessed based on their personality scores, having null and duplicate entries and columns would result in the outcome having skewed, incorrect, or inaccurate data. To avoid this, the rows and columns in the data frame are cleaned, which includes dropping and removing the null and duplicate entries.

The newly created data frame needs to be cleaned so that any duplicate rows, based on the applicant's ID, are removed.

In [5]:
personality_df = raw_personality_df.drop_duplicates(subset=["ID"], keep="last")

All the empty columns will be dropped and cleaned. Furthermore, the names of the columns in the data frame will be reformatted so that they are appropriate to be column names.

In [6]:
personality_df = personality_df.dropna(axis=1)
personality_df.columns = (
    personality_df.columns.str.removeprefix("Section 5 of 6 [")
    .str.removesuffix(".]")
    .str.removesuffix("]")
)
personality_score_df = personality_df.copy()

The first five entries in the updated and cleaned data frame are shown below.

In [7]:
personality_score_df.head()

,ID,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,...,I often forget to put things back in their proper place,I pay attention to details,I seldom feel blue (down),I spend time reflecting on things,I start conversations,I sympathize with others' feelings,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"

The data frame above shows that the column names have been reformatted so that they are more appropriate as names for the columns of the data frame.

Information is provided on the cleaned and updated data frame's columns.

In [8]:
personality_score_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1555 entries, 0 to 1557
Data columns (total 51 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   ID                                                       1555 non-null   int64
 1   I am always prepared                                     1555 non-null   object
 2   I am easily disturbed                                    1555 non-null   object
 3   I am exacting (demanding) in my work                     1555 non-null   object
 4   I am full of ideas                                       1555 non-null   object
 5   I am interested in people                                1555 non-null   object
 6   I am not interested in abstract ideas                    1555 non-null   object
 7   I am not interested in other people's problems           1555 non-null   object
 8   I am not really interested in others                     1555 non-null   object
 9   I am quick to understand things                          1555 non-null   object
 10  I am quiet around strangers                              1555 non-null   object
 11  I am relaxed most of the time                            1555 non-null   object
 12  I am the life of the party                               1555 non-null   object
 13  I change my mood a lot                                   1555 non-null   object
 14  I do not have a good imagination                         1555 non-null   object
 15  I don't like to draw attention to myself                 1555 non-null   object
 16  I don't mind being the center of attention               1555 non-null   object
 17  I don't talk a lot                                       1555 non-null   object
 18  I feel comfortable around people                         1555 non-null   object
 19  I feel little concern for others                         1555 non-null   object
 20  I feel others' emotions                                  1555 non-null   object
 21  I follow a schedule                                      1555 non-null   object
 22  I get chores done right away                             1555 non-null   object
 23  I get irritated easily                                   1555 non-null   object
 24  I get stressed out easily                                1555 non-null   object
 25  I get upset easily                                       1555 non-null   object
 26  I have a rich vocabulary                                 1555 non-null   object
 27  I have a soft (kind) heart                               1555 non-null   object
 28  I have a vivid imagination                               1555 non-null   object
 29  I have difficulty understanding abstract ideas           1555 non-null   object
 30  I have excellent ideas                                   1555 non-null   object
 31  I have frequent mood swings                              1555 non-null   object
 32  I have little to say                                     1555 non-null   object
 33  I insult people                                          1555 non-null   object
 34  I keep in the background                                 1555 non-null   object
 35  I leave my belongings lying around                       1555 non-null   object
 36  I like order                                             1555 non-null   object
 37  I make a mess of things                                  1555 non-null   object
 38  I make people feel at ease                               1555 non-null   object
 39  I neglect my duties                                      1555 non-null   object
 40  I often feel blue (down)                                 1555 non-null   object
 41  I often forget to put things back in their proper place  1555 non-null   object
 42  I pay attention to details                               1555 non-null   object
 43  I seldom feel blue (down)                                1555 non-null   object
 44  I spend time reflecting on things                        1555 non-null   object
 45  I start conversations                                    1555 non-null   object
 46  I sympathize with others' feelings                       1555 non-null   object
 47  I take time out for others                               1555 non-null   object
 48  I talk to a lot of different people at parties           1555 non-null   object
 49  I use difficult words                                    1555 non-null   object
 50  I worry about things                                     1555 non-null   object
dtypes: int64(1), object(50)
memory usage: 631.7+ KB

The information above indicates that the data frame has been cleaned. The columns with null entries have been dropped. This is evidenced by the "Unnamed" columns not being present and also the number of non-null entries decreasing from 1558 non-null entries to 1555 non-null entries.

An assertion is made to determine if the newly created and cleaned data frame has the expected number of rows and columns. The assertion is made to ensure that the newly created and cleaned data frame, which will be used for further calculations, analysis and interpretation in the project,  does not contain any duplicates. This assertion is made by showing that once the previous data frame, called “raw_personality_df”, is cleaned and processed, it will have the same shape as the current, newly created and cleaned data frame called "personality_score_df".

In [9]:
assert (
    len(pd.unique(pd.Series(raw_personality_df["ID"]))),
    len(raw_personality_df.dropna(axis=1).columns),
) == (
    len(personality_score_df),
    len(personality_score_df.columns),
), "The dataframes you are comparing do not have the same shape - they do not have the same number of rows and/or columns"

## Creating new columns from the personality test subscales scores

The data frame will be updated, and new columns will be added. These new columns will contain the total score for each subscale which is calculated from the personality test scores of the respective applicants.

In [10]:
personality_score_totals_df = personality_score_df.copy()

subscale_dictionary = {
    1: "Extraversion",
    2: "Agreeableness",
    3: "Conscientiousness",
    4: "Emotional stability",
    5: "Openness to experience",
}


def calculate_subscale_score(applicant_scores_row, subscale_name):
    subscale_score = 0

    for score in applicant_scores_row[1:]:
        tuple_score = eval(score)
        subscale_score = np.where(
            subscale_dictionary[tuple_score[0]] == subscale_name,
            subscale_score + tuple_score[1],
            subscale_score + 0,
        )

    return subscale_score


for subscale_name_key in subscale_dictionary:
    personality_score_totals_df[subscale_dictionary[subscale_name_key]] = (
        personality_score_df.apply(
            lambda row: calculate_subscale_score(
                row, subscale_dictionary[subscale_name_key]
            ),
            axis=1,
        )
    ).astype("int64")

The first five entries of the updated data frame are shown which contains the new columns with the personality subscales' scores.

In [11]:
personality_score_totals_df.head()

,ID,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,...,I sympathize with others' feelings,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things,Extraversion,Agreeableness,Conscientiousness,Emotional stability,Openness to experience
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36

The first five entries above indicate that the personality subscale scores and their respective columns have been added to the data frame.

The five newly added columns are "Conscientiousness", "Emotional stability", "Openness to experience", "Agreeableness'' and "Extraversion". These new columns are subscales for the questionnaire the applicants took as part of their application and evaluation.

Each of these columns were calculated by having the applicants' score responses to the questions categorized according to the subscales. With each response, the applicants provided a score as their response to the questions, which were stored as a tuple in the data set. The tuple had two values - the first value indicating which of the subscale the question belonged to and the second value in the tuple indicating the applicants' scored responses.

## Importing the departments dataset

The CSV file below is imported so that the dataset can be used to create the departments data frame. The departments data frame will then be used to merge it with the personality score totals data frame to create a merged data frame.

In [12]:
departments_df = pd.read_csv("../data/departments.csv", sep=";")

merged_personality_department_df = pd.concat(
    [
        personality_score_totals_df.reset_index(drop=True),
        departments_df["Department"].str.title().reset_index(drop=True),
    ],
    axis=1,
)

An assertion is made to determine if the newly created data frame has the expected shape and size. The newly created data frame should have the same number of rows as the "personality_score_totals_df" and it should have one column more than "personality_score_totals_df". The newly created data frame has one column more than "personality_score_totals_df" because the newly created data frame is the same as "personality_score_totals_df" with a column for the applicants' departments that they applied to being added to "personality_score_totals_df".

In [13]:
assert merged_personality_department_df.shape == (
    len(personality_score_totals_df),
    len(personality_score_totals_df.columns) + 1,
), "The dataframe does not have the expected shape - it has the incorrect number of rows and/or columns"

The first five entries in the merged personality and department data frame are displayed.

In [14]:
merged_personality_department_df.head()

,ID,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,...,I take time out for others,I talk to a lot of different people at parties,I use difficult words,I worry about things,Extraversion,Agreeableness,Conscientiousness,Emotional stability,Openness to experience,Department
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42,Data
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42,Data
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42,Data
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(2, 5)","(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38,Data
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36,Data

Given that the assertions were true, the above displayed first five entries indicate that the data frames were successfully merged.

## Filtering the merged data frame

A risk status data frame is created from the newly merged data frame, which is filtered to determine which applicants are low and high risk based on their emotional stability, conscientiousness, and agreeableness subscale scores. The newly created risk status data frame is then updated to include a column for the applicants' risk status.

In [15]:
risk_status_df = merged_personality_department_df.copy()

for employee_id in range(len(merged_personality_department_df)):
    risk_status_df.at[employee_id, "Risk Status"] = np.where(
        (
            merged_personality_department_df["Emotional stability"].iloc[employee_id]
            < 30
            and merged_personality_department_df["Conscientiousness"].iloc[employee_id]
            < 30
            and merged_personality_department_df["Agreeableness"].iloc[employee_id] < 30
        ),
        "High risk",
        "Low risk",
    )

The first five entries in the new risk status data frame are displayed below.

In [16]:
risk_status_df.head()

,ID,I am always prepared,I am easily disturbed,I am exacting (demanding) in my work,I am full of ideas,I am interested in people,I am not interested in abstract ideas,I am not interested in other people's problems,I am not really interested in others,I am quick to understand things,...,I talk to a lot of different people at parties,I use difficult words,I worry about things,Extraversion,Agreeableness,Conscientiousness,Emotional stability,Openness to experience,Department,Risk Status
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42,Data,Low risk
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42,Data,Low risk
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42,Data,Low risk
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38,Data,Low risk
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36,Data,Low risk

The first five entries above indicate that the risk status for the respective applicants has been successfully calculated and that the data frame contains a new column for the respective risk statuses.

## Wrangling a new data frame

The respective high and low risk totals for the respective departments is calculated so that a risk status summary data frame can be created.

In [17]:
department_column_names_list = [
    "Risk Status",
    "Copywriting",
    "Data",
    "Design",
    "Strategy",
    "Web Dev",
]

risk_status_summary_df = pd.DataFrame(columns=department_column_names_list)

risk_status_summary_df["Risk Status"] = ["Low Risk", "High Risk"]


def risk_score_calculator(department):
    risk_grouped_by_department_name = risk_status_df.groupby("Department").get_group(
        department
    )["Risk Status"]

    low_risk_score = 0
    high_risk_score = 0

    for risk_status in risk_grouped_by_department_name:
        if risk_status == "Low risk":
            low_risk_score += 1

        else:
            high_risk_score += 1

    risk_status_summary_df[department] = [low_risk_score, high_risk_score]


for department in department_column_names_list[1:]:
    risk_score_calculator(department)

The risk status summary totals are displayed for the respective departments.

In [18]:
display(risk_status_summary_df.style.hide())

With the risk status table, each department was analyzed for potential high and low risk applicants. This was done by checking which applicants had a total score of less than 30 in the "Agreeableness", "Conscientiousness", and "Emotional stability" categories. If an applicant has a score of less than 30 in all three respective categories, then they are deemed "High risk".

Only 2 applicants are high risk based on the risk status summary. This indicates that 0.12% of the applicants are high risk while 99.88% of the applicants are low risk.

# Conclusion

Using the various datasets, methods and calculations, certain outcomes and values can be determined based on conditions and the personality scores of the respective applicants to decide the outcome of their applications.

From the calculations made based on the applicants' personality scores, only 2 applicants are high risk based on the risk status summary. This indicates that 0.12% of the applicants are high risk while 99.88% of the applicants are low risk based on the personality scores they took as part of their application. 

As such, this indicates that there is an overwhelming number of applicants who are low risk while the high risk applicants only represent a minute number of the applicants.